Listen 8080
Listen 8081

<VirtualHost *:8080>
    DocumentRoot /var/www/html/frontend/web
    <Directory /var/www/html/frontend/web>
        AllowOverride All
        Require all granted
        Options FollowSymLinks
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/frontend-error.log
    CustomLog ${APACHE_LOG_DIR}/frontend-access.log combined
</VirtualHost>

<VirtualHost *:8081>
    DocumentRoot /var/www/html/backend/web
    <Directory /var/www/html/backend/web>
        AllowOverride All
        Require all granted
        Options FollowSymLinks
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/backend-error.log
    CustomLog ${APACHE_LOG_DIR}/backend-access.log combined
</VirtualHost>
